prjWebApplication1/Models/Discount.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace prjWebApplication1.Models
{
    public partial class Discount
    {
        public Discount()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int RoomDiscountId { get; set; }
        public string DiscountName { get; set; }
        public string DiscountInfo { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

prjWebApplication1/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Mvc;
using pjGuesthouse.ViewModels;
using prjWebApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pjGuesthouse.Controllers
{
    public class DiscountController : Controller
    {
        public IActionResult DiscountMain()
        {
            var data = queryAll();
            return View(data);
        }

        public IActionResult DiscountAdmin()
        {
            var data = queryAll();
            return View(data);
        }
        [HttpPost]
        public IActionResult DiscountAdmin(DisViewModel model)
        {
            IEnumerable<Discount> data;
            if (string.IsNullOrEmpty(model.txtKey))
                data = queryAll();
            else
                data = from d in (new MingSuContext()).Discounts
                       where (d.DiscountInfo.Contains(model.txtKey) ||
                       d.DiscountName.Contains(model.txtKey))
                       select d;
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Discount d)
        {
            if (string.IsNullOrEmpty(d.DiscountInfo) || string.IsNullOrEmpty(d.DiscountName))
                return View();
            MingSuContext db = new MingSuContext();
            db.Discounts.Add(d);
            db.SaveChanges();
            return RedirectPermanent("DiscountAdmin");
        }

        public IActionResult Delete(int? Id)
        {
            MingSuContext db = new MingSuContext();
            Discount d = db.Discounts.FirstOrDefault(d => d.RoomDiscountId == Id);
            if (d != null)
            {
                db.Discounts.Remove(d);
                db.SaveChanges();
            }
            return RedirectToAction("DiscountAdmin");
        }

        public IActionResult Edit(int? Id)
        {
            if (Id != null)
            {
                MingSuContext db = new MingSuContext();
                Discount d = db.Discounts.FirstOrDefault(d => d.RoomDiscountId == Id);
                if (d != null)
                    return View(d);
            }
            return RedirectPermanent("DiscountAdmin");
        }
        [HttpPost]
        public IActionResult Edit(DisViewModel input)
        {
            MingSuContext db = new MingSuContext();
            Discount d = db.Discounts.FirstOrDefault(d => d.RoomDiscountId == input.Id);
            if (d != null)
            {
                d.DiscountInfo = input.DiscountInfo;
                d.DiscountName = input.DiscountName;
                db.SaveChanges();
            }
            return RedirectToAction("DiscountAdmin");
        }
        public IEnumerable<Discount> queryAll()
        {
            var data = from d in (new MingSuContext()).Discounts
                       select d;
            return data;
        }
    }
}

prjWebApplication1/Views/Discount/Create.cshtml
@model prjWebApplication1.Models.Discount

@{
    ViewData["Title"] = "Create";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

<h1>優惠管理系統</h1>

<h4>新增優惠資料</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">優惠名稱</label>
                <input asp-for="DiscountName" class="form-control" />
                <span asp-validation-for="DiscountName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">優惠折扣</label>
                <input asp-for="DiscountInfo" class="form-control" />
                <span asp-validation-for="DiscountInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="新增資料" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="DiscountAdmin">回上頁</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prjWebApplication1/Views/Discount/DiscountAdmin.cshtml
@model IEnumerable<prjWebApplication1.Models.Discount>

@{
    ViewData["Title"] = "DiscountAdmin";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<link href="~/css/ForTable.css" rel="stylesheet" />

<br />
<p style="font-size:30px" class="forp">優惠一覽表</p>
<div class="forp">
    @using (Html.BeginForm())
    {
        @:關鍵字 @Html.TextBox("txtKeyword", "", new { @class = "form-control" }) <input type="submit" value="查詢" class="btn btn-secondary" />
    }
    <br />
    <p>
        <a asp-action="Create" class="btn btn-dark">新增資料</a>
    </p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                序列
            </th>
            <th>
                優惠名稱
            </th>
            <th>
                優惠折扣
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 0;
            foreach (var item in Model)
            {
                i++;
                <tr>
                    <td>
                        @i
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiscountName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiscountInfo)
                    </td>
                    <td>
                        @Html.ActionLink("編輯", "Edit", new { id = item.RoomDiscountId }, new { @class = "btn btn-dark" }) |
                        @Html.ActionLink("刪除", "Delete", "Discount", new { id = item.RoomDiscountId },
                        new { onclick = "return confirm('確定要刪除嗎?')", @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

prjWebApplication1/Views/Discount/DiscountMain.cshtml
@model IEnumerable<pjGuesthouse.Models.Discount>

@{
    ViewData["Title"] = "DiscountMain";
}

<h1>優惠折扣</h1>
<div>
    <div class="container p-lg-5 p-3 wow bounceInUp">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-sm-6 mb-4">
                    <div class="card" style="height:130px">
                        <img src=""
                             class="card-img-top" />
                        <div class="card-body">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.DiscountName)</h5>
                            <p class="card-text">
                                @Html.DisplayFor(modelItem => item.DiscountInfo)
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

prjWebApplication1/Views/Discount/Edit.cshtml
@model pjGuesthouse.Models.Discount

@{
    ViewData["Title"] = "Edit";
}

<h1>優惠管理系統</h1>

<h4>修改優惠資料</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="RoomDiscountId" class="control-label"></label>
                <input asp-for="RoomDiscountId" class="form-control" />
                <span asp-validation-for="RoomDiscountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">優惠名稱</label>
                <input asp-for="DiscountName" class="form-control" />
                <span asp-validation-for="DiscountName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">優惠折扣</label>
                <input asp-for="DiscountInfo" class="form-control" />
                <span asp-validation-for="DiscountInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="儲存" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="DiscountAdmin">回上頁</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}